Repository SCCapstone/Group16, pull requests merged in 2025-04, with the labels that each got.

#437 Update Angular to version 19
  src/fe-app/package-lock.json
  src/fe-app/package.json
  src/fe-app/server.ts
  src/fe-app/src/app/app.component.ts
  src/fe-app/src/app/grade-calc/grade-calc.component.ts
  src/fe-app/src/app/home/home.component.ts
  src/fe-app/src/app/login/login.component.ts
  src/fe-app/src/app/main/add-task/add-task.component.ts
  src/fe-app/src/app/main/calendar/calendar.component.ts
  src/fe-app/src/app/main/courses-sidebar/courses-sidebar.component.ts
  src/fe-app/src/app/main/edit-task/edit-task.component.ts
  src/fe-app/src/app/main/grades/grades.component.ts
  src/fe-app/src/app/main/main.component.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.ts
  src/fe-app/src/app/main/task-list/task-list.component.ts
  src/fe-app/src/app/main/task-list/task/task.component.ts
  src/fe-app/src/app/notifications/notifications.component.ts
  src/fe-app/src/app/settings/appearance-settings/appearance-settings.component.ts
  src/fe-app/src/app/settings/notification-settings/notification-settings.component.ts
  src/fe-app/src/app/settings/profile-settings/profile-settings.component.ts
  src/fe-app/src/app/settings/settings-sidebar/settings-sidebar.component.ts
  src/fe-app/src/app/settings/settings.component.ts
Labels: pull request

#431 Add more tasks
  src/fe-app/src/app/main/add-task/add-task.component.css
  src/fe-app/src/app/main/add-task/add-task.component.html
  src/fe-app/src/app/main/add-task/add-task.component.ts
Labels: pull request, fe

#435 Rework Settings Buttons to Match New Layout
  src/fe-app/src/app/settings.service.spec.ts
  src/fe-app/src/app/settings.service.ts
  src/fe-app/src/app/settings/notification-settings/notification-settings.component.html
  src/fe-app/src/app/settings/notification-settings/notification-settings.component.spec.ts
  src/fe-app/src/app/settings/notification-settings/notification-settings.component.ts
  src/fe-app/src/app/settings/profile-settings/profile-settings.component.css
  src/fe-app/src/app/settings/profile-settings/profile-settings.component.html
  src/fe-app/src/app/settings/profile-settings/profile-settings.component.spec.ts
  src/fe-app/src/app/settings/profile-settings/profile-settings.component.ts
  src/fe-app/src/app/settings/settings.component.css
  src/fe-app/src/app/settings/settings.component.html
  src/fe-app/src/app/settings/settings.component.ts
Labels: enhancement, pull request

#442 Implement Backend Cookies
  src/be/pom.xml
  src/be/src/main/java/group16/be/AuthFilter.java
  src/be/src/main/java/group16/be/RequestHandler.java
  src/be/src/main/java/group16/be/SecurityConfig.java
  src/be/src/main/java/group16/be/TokenService.java
  src/be/src/main/java/group16/be/WebConfig.java
  src/be/src/test/java/group16/be/AuthFilterTests.java
  src/be/src/test/java/group16/be/RequestHandlerTests.java
Labels: pull request, be

#447 Update Kubernetes build script and refine CORS configuration in WebCo…
  .k8s/build_k8s.bash
  src/be/src/main/java/group16/be/WebConfig.java
Labels: pull request, be

#438 Add mobile phone handling to User class and corresponding tests
  src/be/src/main/java/group16/be/db/User.java
  src/be/src/test/java/group16/be/UserTests.java
Labels: pull request

#445 Due Soon Sidebar Fixes
  src/fe-app/src/app/assignment.service.ts
  src/fe-app/src/app/main/courses-sidebar/courses-sidebar.component.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.ts
Labels: bug

#450 Overhaul Calendar
  src/fe-app/public/images/left-arrow.png
  src/fe-app/public/images/right-arrow.png
  src/fe-app/src/app/main/calendar/calendar.component.css
  src/fe-app/src/app/main/calendar/calendar.component.html
  src/fe-app/src/app/main/calendar/calendar.component.ts
Labels: enhancement

#454 Fixed final grade decimal point to 2 places
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.ts
Labels: bug

#478 Front-End Unit Testing
  src/fe-app/src/app/app.component.spec.ts
  src/fe-app/src/app/app.component.ts
  src/fe-app/src/app/assignment.service.ts
  src/fe-app/src/app/auth.guard.ts
  src/fe-app/src/app/course.service.spec.ts
  src/fe-app/src/app/course.service.ts
  src/fe-app/src/app/grades.service.ts
  src/fe-app/src/app/heartbeat.service.ts
  src/fe-app/src/app/login.service.ts
  src/fe-app/src/app/main/add-task/add-task.component.spec.ts
  src/fe-app/src/app/main/edit-task/edit-task.component.html
  src/fe-app/src/app/main/edit-task/edit-task.component.spec.ts
  src/fe-app/src/app/main/edit-task/edit-task.component.ts
  src/fe-app/src/app/main/grades/grades.component.spec.ts
  src/fe-app/src/app/main/grades/grades.component.ts
  src/fe-app/src/app/main/main.component.spec.ts
  src/fe-app/src/app/main/main.component.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.spec.ts
  src/fe-app/src/app/main/task-list/task-list.component.html
  src/fe-app/src/app/main/task-list/task-list.component.spec.ts
  src/fe-app/src/app/main/task-list/task-list.component.ts
  src/fe-app/src/app/main/task-list/task/task.component.spec.ts
  src/fe-app/src/app/main/task-list/task/task.component.ts
  src/fe-app/src/app/notifications/notifications.component.spec.ts
  src/fe-app/src/app/notifications/notifications.component.ts
Labels: pull request, fe, testing

#497 Various Front End Fixes
  src/fe-app/src/app/login/login.component.html
  src/fe-app/src/app/main/edit-task/edit-task.component.css
  src/fe-app/src/app/main/edit-task/edit-task.component.html
  src/fe-app/src/app/main/edit-task/edit-task.component.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.spec.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.ts
Labels: bug, pull request, fe

#490 Calendar 1.0 Fixes
  src/fe-app/public/images/checkmark.png
  src/fe-app/public/images/urgent.png
  src/fe-app/src/app/main/calendar/calendar.component.css
  src/fe-app/src/app/main/calendar/calendar.component.html
  src/fe-app/src/app/main/calendar/calendar.component.spec.ts
  src/fe-app/src/app/main/calendar/calendar.component.ts
  src/fe-app/src/app/main/main.component.css
  src/fe-app/src/app/main/task-list/task-list.component.spec.ts
  src/fe-app/src/styles.css
Labels: pull request, fe

#501 Tested the Heartbeat Service
  src/fe-app/src/app/heartbeat.service.spec.ts
Labels: pull request, fe, testing

#503 Fix Final Grade Not Updating on Grade Change
  src/fe-app/src/app/grades.service.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.ts
Labels: pull request, fe

#504 Fix Long Words Not Breaking in Task List and Grades
  src/fe-app/src/app/main/grades/grades.component.css
  src/fe-app/src/app/main/task-list/task/task.component.css
Labels: pull request, fe

#505 tab fix and adding time
  src/fe-app/src/app/main/add-task/add-task.component.html
  src/fe-app/src/app/main/calendar/calendar.component.html
  src/fe-app/src/app/main/main.component.css
  src/fe-app/src/app/main/main.component.html
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.html
  src/fe-app/src/app/main/task-list/task/task.component.html
Labels: enhancement, fe

#506 Remove alert() and confirm()
  src/fe-app/src/app/login/login.component.css
  src/fe-app/src/app/login/login.component.html
  src/fe-app/src/app/login/login.component.spec.ts
  src/fe-app/src/app/login/login.component.ts
  src/fe-app/src/app/main/add-task/add-task.component.css
  src/fe-app/src/app/main/add-task/add-task.component.html
  src/fe-app/src/app/main/add-task/add-task.component.ts
  src/fe-app/src/app/main/edit-task/edit-task.component.css
  src/fe-app/src/app/main/edit-task/edit-task.component.html
  src/fe-app/src/app/main/edit-task/edit-task.component.ts
  src/fe-app/src/app/main/task-list/task-list.component.spec.ts
  src/fe-app/src/app/main/task-list/task-list.component.ts
  src/fe-app/src/app/main/task-list/task/task.component.css
  src/fe-app/src/app/main/task-list/task/task.component.html
  src/fe-app/src/app/main/task-list/task/task.component.spec.ts
  src/fe-app/src/app/main/task-list/task/task.component.ts
  src/fe-app/src/app/notifications/notifications.component.spec.ts
  src/fe-app/src/app/notifications/notifications.component.ts
  src/fe-app/src/app/settings/settings.component.spec.ts
  src/fe-app/src/app/settings/settings.component.ts
Labels: bug, pull request, fe

#510 Replace Generic Settings Save Error
  src/fe-app/src/app/settings/settings.component.html
  src/fe-app/src/app/settings/settings.component.ts
Labels: pull request, fe

#511 Sorting Enhancements
  src/fe-app/public/images/sort.png
  src/fe-app/public/images/sorting-asc.png
  src/fe-app/public/images/sorting-desc.png
  src/fe-app/src/app/main/task-list/task-list.component.css
  src/fe-app/src/app/main/task-list/task-list.component.html
  src/fe-app/src/app/main/task-list/task-list.component.spec.ts
  src/fe-app/src/app/main/task-list/task-list.component.ts
Labels: enhancement, pull request, fe

#515 Add Loading Screen To Task List, Calendar, and Grades Pages
  src/fe-app/src/app/main/calendar/calendar.component.css
  src/fe-app/src/app/main/calendar/calendar.component.html
  src/fe-app/src/app/main/grades/grades.component.css
  src/fe-app/src/app/main/grades/grades.component.html
  src/fe-app/src/app/main/grades/grades.component.spec.ts
  src/fe-app/src/app/main/grades/grades.component.ts
  src/fe-app/src/app/main/main.component.css
  src/fe-app/src/app/main/task-list/task-list.component.css
  src/fe-app/src/app/main/task-list/task-list.component.html
Labels: pull request, fe

#523 Fixed outdated grade id with current
  src/be/src/test/java/group16/be/NotificationTests.java
Labels: bug, testing

#526 Javadoc frontend
  src/fe-app/src/app/app.component.ts
  src/fe-app/src/app/assignment.service.ts
  src/fe-app/src/app/grade-calc/grade-calc.component.ts
  src/fe-app/src/app/grades.service.ts
  src/fe-app/src/app/home/home.component.ts
  src/fe-app/src/app/login/login.component.ts
  src/fe-app/src/app/main/add-task/add-task.component.ts
  src/fe-app/src/app/main/calendar/calendar.component.ts
  src/fe-app/src/app/main/courses-sidebar/courses-sidebar.component.ts
  src/fe-app/src/app/main/edit-task/edit-task.component.ts
  src/fe-app/src/app/main/grades/grades.component.ts
  src/fe-app/src/app/main/main.component.ts
  src/fe-app/src/app/main/secondary-sidebar/secondary-sidebar.component.ts
  src/fe-app/src/app/main/task-list/task-list.component.ts
  src/fe-app/src/app/main/task-list/task/task.component.ts
  src/fe-app/src/app/notifications/notifications.component.ts
  src/fe-app/src/app/settings/appearance-settings/appearance-settings.component.ts
  src/fe-app/src/app/settings/notification-settings/notification-settings.component.ts
  src/fe-app/src/app/settings/profile-settings/profile-settings.component.ts
  src/fe-app/src/app/settings/settings-sidebar/settings-sidebar.component.ts
  src/fe-app/src/app/settings/settings.component.ts
Labels: pull request, fe

#527 Behavioral Test Enhancement
  src/fe-app/playwright.config.ts
Labels: enhancement
